---
name: Bug report
description: Create a report to help us improve
title: "[BUG]"
labels: [ "bug" ]
assignees: []
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the bug
      placeholder: ""
      value: ""
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: 
      placeholder: e.g. iOS
    validations:
      required: false
---

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
