---
name: Bug report
description: Create a report to help us improve
title: "[BUG]"
labels: [ "bug" ]
assignees: []
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the bug
      placeholder: "A clear and concise description of what the bug is."
      value: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: "How do you trigger this bug? Please walk us through it step by step."
      value: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
        ...
      render: bash
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
        If applicable, add screenshots to help explain your problem.
      placeholder: "A clear and concise description of what the bug is."
      value: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: input
    id: os
    attributes:
      label: Operating system
      description: 
      placeholder: e.g. iOS
    validations:
      required: false
  - type: input
    id: browser
    attributes:
      label: Browser
      description:
      placeholder: e.g. Google Chrome, Mozilla Firefox, Microsoft Edge, Safari, Opera
    validations:
      required: false
  - type: input
    id: browser-version
    attributes:
      label: Browser version
      description:
      placeholder: e.g. 42
    validations:
      required: false
---


**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
